### ISSUE TITLE
signup page with overlay effect

### ISSUE THREAD

**Issue by AnandDhakane01** [arc-pune/arc-front-end#100]
signup page needed. You can refer to the login page. we need an exact clone only the text fields and buttons will change. overlay effect. refer Figma link which is in the readme file.

**Comment by AjayPrabuR** [comment]
1.  I would like to know that is this the [Figma design](https://www.figma.com/proto/BqzGoxY6C9eHFbqa2EPpZE/ARC?node-id=8%3A8&scaling=min-zoom&page-id=0%3A1) you are mentioning for the signup page?

2. Also would like to get better understanding on **overlay effect**
