### ISSUE TITLE
[BUG] Incorrect font used at multiple pages

### ISSUE THREAD

**Issue by sanjaybaskaran01** [arc-pune/arc-front-end#113]
**Describe the bug**
Font displayed is serif but the font that should be displayed is Roboto

**To Reproduce**
1. Go to https://arc-pune.vercel.app/
2. Click on Login or about page

**Expected behavior**
![image](https://user-images.githubusercontent.com/72266283/136653044-df0de46b-81fb-4bac-9275-4d4566e4ecb8.png)
![image](https://user-images.githubusercontent.com/72266283/136653318-0c243260-93e5-4855-ad51-a26956300a46.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/72266283/136653340-169d26c6-a25a-446f-b8e5-cdd3130decf3.png)

![image](https://user-images.githubusercontent.com/72266283/136652954-a11cd4de-96bc-4b93-87b9-68805582fd28.png)

**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Browser Chromium

**Comment by agarwalsahil0210** [comment]
Hey, thank you for pointing this error out. You can start working on this and then send the pr when you are done. And also keep us updated. You can also join our discord for a detailed discussion.

**Comment by kamal-kaur04** [comment]
Hi @agarwalsahil0210, Can I take up this issue if this is not resolved yet? Thanks.

**Comment by sanjaybaskaran01** [comment]
I think this has been already resolved @kamal-kaur04 , I will unassign myself and close this issue
