### ISSUE TITLE
Improving UI of the present webpage.

### ISSUE THREAD

**Issue by mohittk** [arc-pune/arc-front-end#12]

**Comment by rohancodex** [comment]
Can I work on this issue?

Here are a few changes I would like to make:

1. The login and signup buttons and the main CTA button can have better hover states. Also there need not be 2 buttons saying login and signup but rather one button saying signup and then it could ask if the user has an account and wants to login.
2.  The navbar links can have an underline on hover.
3.  The heading needs some padding and a better typography I guess.

**Comment by AnandDhakane01** [comment]
yup, glad you are willing to contribute to this project. I've assigned you the issue. you can start working!
