### ISSUE TITLE
Unable to join discord

### ISSUE THREAD

**Issue by qwel-exe** [arc-pune/arc-front-end#128]
hey i am not able to join discord or message any one :( could I know why pls

**Comment by qwel-exe** [comment]
if you banded me could i know the reason

**Comment by qwel-exe** [comment]
+ i got hacked becase the link send by @majjikishore007 in my dm (discord nitro scam thing )
and also the servers i was admin on got nunked (all chanalles got deleted and one new chanall was made called Free nitro and it pined everyone and gave the discord scam link  )

**Comment by qwel-exe** [comment]
:angry: :anger: ()

**Comment by majjikishore007** [comment]
> * i got hacked becase the link send by @majjikishore007 in my dm (discord nitro scam thing )
>   and also the servers i was admin on got nunked (all chanalles got deleted and one new chanall was made called Free nitro and it pined everyone and gave the discord scam link  )

my account too got hacked bro sorry for my mistake

**Comment by qwel-exe** [comment]
> > * i got hacked becase the link send by @majjikishore007 in my dm (discord nitro scam thing )
> >   and also the servers i was admin on got nunked (all chanalles got deleted and one new chanall was made called Free nitro and it pined everyone and gave the discord scam link  )
> 
> my account too got hacked bro sorry for my mistake

np bro I got my account back I thought you banned me because I did something
