### ISSUE TITLE
Change the theme toggle icon

### ISSUE THREAD

**Issue by agarwalsahil0210** [arc-pune/arc-front-end#132]
A relevant icon for changing the theme from light to dark mode and vice-versa.

**Comment by timagixe** [comment]
@agarwalsahil0210 hi, is there any specific icon you want to be used for theme switcher?

Or those can be sun / moon icons of [heroicons](https://heroicons.com)?

Should different icons to be displayed for different active theme? (i.e. when active light theme the moon icon should be displayed, when active dark theme the sun icon should be displayed)

**Comment by agarwalsahil0210** [comment]
> @agarwalsahil0210 hi, is there any specific icon you want to be used for theme switcher?
> 
> Or those can be sun / moon icons of [heroicons](https://heroicons.com)?
> 
> Should different icons to be displayed for different active theme? (i.e. when active light theme the moon icon should be displayed, when active dark theme the sun icon should be displayed)

Hey @timagixe you got that. There should be different icons displayed for different active theme. And the sun / moon icons would work!. Should i assign you this?

**Comment by timagixe** [comment]
@agarwalsahil0210 yes, please. Would be happy to contribute.

**Comment by agarwalsahil0210** [comment]
> @agarwalsahil0210 yes, please. Would be happy to contribute.

Okay I've assigned this to you . Just once go through `Contributing.md` and get started. Happy Coding!

**Comment by timagixe** [comment]
@agarwalsahil0210 I did the job in #136. Please take a look once you have a chance.

**Comment by agarwalsahil0210** [comment]
> @agarwalsahil0210 I did the job in #136. Please take a look once you have a chance.

Okay that seems pretty good. I'll be merging this. Thanks for your contribution! Cheers!
