### ISSUE TITLE
There are just too many issues to describe in the title, so read the description

### ISSUE THREAD

**Issue by shishirtiwari23** [arc-pune/arc-front-end#25]
## What are the Issues ?
- There are no Routes in App.js
- The Buttons Don't Work 
- On Hover the "SignUp" button seems to lose focus UI wise
- navbar links don't work

## On a Separate Note:
Thanks for Thinking about animals, you are doing Gods work ❤️, I too am an animal activist and would love to work with you !!

# Thank You ❤️

**Comment by shishirtiwari23** [comment]
@AnandDhakane01 I will work on this issue right away , Could you please assign me this issue

**Comment by AnandDhakane01** [comment]
> ## What are the Issues ?
> * There are no Routes in App.js
> * The Buttons Doesn't Work
> * On Hover the "SignUp" button seems to loose focus UI wise
> * navbar links doesn't work
> 
> ## On a Separate Note:
> Thanks for Thinking about animals, you are doing Gods work heart, I too am an animal activist and would love to work with you !!
> 
> # Thank You

Hii Shishir, I get you, we are currently working on different web pages that will be linked to the navbar buttons. A basic figma file will be ready soon, we will assign you the issue as soon as we have the design template ready!

**Comment by shishirtiwari23** [comment]
@AnandDhakane01 Keep up the good work and let me know when the design is ready !! and Thanks again for helping animals !!

**Comment by diptilulla** [comment]
Can I also work on frontend after designs are ready?

**Comment by AnandDhakane01** [comment]
Hii, we have divided this issue into multiple features to be implemented. You can check those out, or wait for some time we'll be raising more issues. I'll have to close this issue for now..
