### ISSUE TITLE
Comment on Home.js [Label: Typo/Bug]

### ISSUE THREAD

**Issue by aniketnegii** [arc-pune/arc-front-end#26]
Comment on Home.js is visible.
Comment : //nav bar

**Comment by aniketnegii** [comment]
Can I fix it? 
If yes do I have to create a separate branch to push the changes before creating a pull request or I can push directly to main.

**Comment by AnandDhakane01** [comment]
Thanks for spotting, looks like a very small bug, people working on the homepage have already sorted it out. If you are interested in contributing you can check out other issues.
