### ISSUE TITLE
Bug in the navbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [arc-pune/arc-front-end#29]
**Describe the bug**
On clicking Adopt or About on the navbar, the bottom border does not shift (to the one that is clicked).

**Comment by KarishmaVanwari** [comment]
Hey, can I fix this as a part of Hacktoberfest 2021? @AnandDhakane01 @majjikishore007

**Comment by AnandDhakane01** [comment]
> Hey, can I fix this as a part of Hacktoberfest 2021? @AnandDhakane01 @majjikishore007

Hii, we are glad you are willing to contribute, we have actually decided to change the complete UI/UX of the site to a much better design and theme. You can check out the design here [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1). Let me know if you are willing to work on any of the unassigned pages.

**Comment by KarishmaVanwari** [comment]
> > Hey, can I fix this as a part of Hacktoberfest 2021? @AnandDhakane01 @majjikishore007
> 
> Hii, we are glad you are willing to contribute, we have actually decided to change the complete UI/UX of the site to a much better design and theme. You can check out the design here [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1). Let me know if you are willing to work on any of the unassigned pages.

Yup, sure!

**Comment by AnandDhakane01** [comment]
We were thinking of assigning you the adopt us page. you can create the issue. Hop onto our discord server for a quick call. You will find the link in the readme file.
