### ISSUE TITLE
Dockerize Repo

### ISSUE THREAD

**Issue by duaimei** [arc-pune/arc-front-end#32]
**Is your feature request related to a problem? Please describe.**
Having a docker option for development will help new contributors get setup faster sicne development environments can vary drastically.

https://www.zdnet.com/article/what-is-docker-and-why-is-it-so-darn-popular/

**Comment by AnandDhakane01** [comment]
> **Is your feature request related to a problem? Please describe.** Having a docker option for development will help new contributors get setup faster sicne development environments can vary drastically.
> 
> https://www.zdnet.com/article/what-is-docker-and-why-is-it-so-darn-popular/

Hii, thanks a lot for you PR, we've merged the PR and have also given the hacktoberfest-accepted label. If you would like to contribute more, you can check out other issues.
