### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by majjikishore007** [arc-pune/arc-front-end#4]
create a login page

**Comment by MuditWadhwa** [comment]
Hi,I wish to contribute to this repository. Please assign this issue to me.

**Comment by majjikishore007** [comment]
ya sure you can contribute, we need a simple login and make sure to follow the same design pattern that of the home page.
you can join us on discord for more insights link in the readme file  😊

**Comment by mayankgoyal-13** [comment]
Hi, I would like to contribute. Can you assign it to me.

**Comment by TD-17** [comment]
Hey! I want to contribute. I have also made many open source contributions in the past. Please assign this issue to me.

**Comment by Mohamed-Ayaan358** [comment]
Hey I can work on this. May I be assigned to this issue?

**Comment by majjikishore007** [comment]
hey @Mohamed-Ayaan358 I have assigned you the issue you can start working on, feel free to reach out to us on discord for any queries

**Comment by Mohamed-Ayaan358** [comment]
> hey @Mohamed-Ayaan358 I have assigned you the issue you can start working on, feel free to reach out to us on discord for any queries

Hey there @majjikishore007 I've been requested to join as a maintainer in another repository (I already have a busy schedule) I am terribly sorry but may I be designed from this issue?

**Comment by Mr-G-D** [comment]
I can do this task in an efficient way. May I be assigned to this issue?

**Comment by AnandDhakane01** [comment]
> Hey! I want to contribute. I have also made many open source contributions in the past. Please assign this issue to me.

Hii there, glad you are willing to contribute, I'll assign you this issue.

**Comment by kaushiki29** [comment]
Hi I want to work on this issue, can you assign it to me?

**Comment by AnandDhakane01** [comment]
Hey assignees, we have the Figma template ready!!, you guys can start working on these designs.
 [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)

**Comment by TD-17** [comment]
> Hey assignees, we have the Figma template ready!!, you guys can start working on these designs. [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)

From where can I take the images for the login page ?

**Comment by kaushiki29** [comment]
> Hey assignees, we have the Figma template ready!!, you guys can start working on these designs. [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)

Only the assignees need to work ? or we too can contribute?

**Comment by majjikishore007** [comment]
> > Hey assignees, we have the Figma template ready!!, you guys can start working on these designs. [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)
> 
> From where can I take the images for the login page?

use the Figma file and export from there

**Comment by majjikishore007** [comment]
> > Hey assignees, we have the Figma template ready!!, you guys can start working on these designs. [design](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)
> 
> Only the assignees need to work? or we too can contribute?

you can also work

**Comment by TD-17** [comment]
@majjikishore007 @AnandDhakane01 Please review my PR.
https://github.com/arc-pune/arc-front-end/pull/51/commits/362b6e5bd55c9cce248412de80b23b131b076224

**Comment by AnandDhakane01** [comment]
> @majjikishore007 @AnandDhakane01 Please review my PR. [362b6e5](https://github.com/arc-pune/arc-front-end/commit/362b6e5bd55c9cce248412de80b23b131b076224)
Hi, we've merged your PR, thanks a lot for your contribution!!
