### ISSUE TITLE
SignUp-page

### ISSUE THREAD

**Issue by majjikishore007** [arc-pune/arc-front-end#5]
create a signup page

**Comment by suprabhat25** [comment]
I want to work on this issue.

**Comment by AnandDhakane01** [comment]
yup, you can start working, we need a simple signup page as of now, we are using tailwindcss, just make sure you match the color theme with other web pages. You can put in the standard links and all for now. Let us know when the layout is ready.

**Comment by Mr-G-D** [comment]
Hey @majjikishore007, may I be assigned to this issue.

**Comment by kaushiki29** [comment]
Hi I want to work on this issue, can you please assign it to me?

**Comment by majjikishore007** [comment]
> Hi I want to work on this issue, can you please assign it to me?

you can work on this issue. This is the design you need to follow  [figma ](https://www.figma.com/file/BqzGoxY6C9eHFbqa2EPpZE/Untitled?node-id=0%3A1)

**Comment by suprabhat25** [comment]
Please clear who is going to work on this issue @majjikishore007 ? It's me or @kaushiki29 ?

**Comment by majjikishore007** [comment]
> Please clear who is going to work on this issue @majjikishore007 ? It's me or @kaushiki29 ?

bro, I guess I have assigned you and you can continue working

**Comment by suprabhat25** [comment]
Ok.

**Comment by majjikishore007** [comment]
> Hey @majjikishore007, may I be assigned to this issue.

sure
