### ISSUE TITLE
Footer-component

### ISSUE THREAD

**Issue by majjikishore007** [arc-pune/arc-front-end#6]
create a footer component for the home page

**Comment by suprabhat25** [comment]
I want to work on this issue.

**Comment by dhanushp** [comment]
@majjikishore007 Could you please provide more information? What details would you like to add to Footer?

**Comment by majjikishore007** [comment]
@dhanushp @suprabhat25  for details join our  [discord server](https://discord.gg/6PRRGBUn)

**Comment by TD-17** [comment]
Hey! Could you please assign this issue to me? I want to make my contribution to this repository.

**Comment by majjikishore007** [comment]
@TD-17  yes you can start working, we have assigned you

**Comment by majjikishore007** [comment]
hey @dhanushp  i have assigned the issue to you , and now you can start working, feel free to reach out on Disocrd
