### ISSUE TITLE
Gallery-component

### ISSUE THREAD

**Issue by majjikishore007** [arc-pune/arc-front-end#7]
make a gallery component for the home page to display featured adoptions

**Comment by hellodeborahuk** [comment]
Can I work on this issue please? Do you have a folder of images to work from?

**Comment by AnandDhakane01** [comment]
Hii, you can use sample pet images as of now, once we are ready with the database we will be updating you with the new images.

**Comment by Tejaswi-Chaudhari** [comment]
Hello @majjikishore007 @AnandDhakane01 
If no one is working on this, can I work?
