### ISSUE TITLE
Card-Component

### ISSUE THREAD

**Issue by agarwalsahil0210** [arc-pune/arc-front-end#8]
create a card component that will display the pets which are up for adoption

**Comment by sn2606** [comment]
Hey! I would like to work on this issue.

**Comment by qwe123coder** [comment]
hey i have a idea in my head i would love to work on this

**Comment by satyabrata-mishra** [comment]
I can work on it. Just Provide me the necessary information to be displayed in the card ### **component.******

**Comment by qwe123coder** [comment]
> I can work on it. Just Provide me the necessary information to be displayed in the card component

hey i am done with it

**Comment by qwe123coder** [comment]
hey what happen to this ?
