### ISSUE TITLE
Homepage landing banner and navbar

### ISSUE THREAD

**Issue by AnandDhakane01** [arc-pune/arc-front-end#89]
the landing banner and navbar on the homepage need to be developed according to the design in the Figma file.

**Comment by Juan-A-Jimenez** [comment]
Hi AnandDhakane01,
I am not sure what the landing banner on the homepage is. Do you mean this element:
![screenshot_figma_injuredPaws](https://user-images.githubusercontent.com/54940088/136175028-e1d813ad-f3a9-416d-a44d-629fb1e38839.png)
