### ISSUE TITLE
dark mode toggle button not working

### ISSUE THREAD

**Issue by AnandDhakane01** [arc-pune/arc-front-end#99]
**Describe the bug**
the dark mode feature has already been implemented, but for some reason, the toggle button doesn't seem to work. 
The toggle button is supposed to be on the right of the signup button.

**Expected behavior**
should be able to toggle between dark and light mode, do refer to the Figma link in the readme

**Comment by Ankitlenka26** [comment]
Hey, I can work on this issue. Can you please assign it to me?
